baseURL = "https://www.divide-and-conquer-ago.com/"
languageCode = 'en-us'
title = "Divide and Conquer: AI and Gameplay Overhaul"
theme = ["hugo-shortcode-gallery"]
timeout="120s"
googleAnalytics = "G-XG0DKC8RXC"
enableRobotsTXT = true

[markup.goldmark.renderer]
  unsafe= true

[params]
  description = "A submod for Third Age: Total war - Divide and Conquer"
  longTitle = "Divde and Conquer: AI and Gameplay Overhaul"

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2