baseURL = "https://EddieEldridge.github.io/dac-ago-docs/"
languageCode = 'en-us'
title = "Divide and Conquer: AI and Gameplay Overhaul"
theme = ["hugo-shortcode-gallery"]

[markup.goldmark.renderer]
  unsafe= true

[params]
  description = "A submod for Third Age: Total war - Divide and Conquer"
  longTitle = "Divde and Conquer: AI and Gameplay Overhaul"
  dorwinionColor = "color: #ffb144;"

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2