baseURL = 'http://example.org/'
languageCode = 'en-us'
title = "Divide and Conquer: AI and Gameplay Overhaul"
theme = "hyde"

[params]
  description = "A submod for Third Age: Total war - Divide and Conquer"
  longTitle = "Divde and Conquer: AI and Gameplay Overhaul"

